repos:
  - repo: https://github.com/psf/black
    rev: 20.8b1
    hooks:
      - id: black


  - repo: local
    hooks:
      - id: pytest
        name: Check example tests
        entry: pytest
        pass_filenames: false
        language: system
        types: [python]
      - id: mypy
        name: Check typing
        entry: mypy faux_sures
        pass_filenames: false
        language: system
        types: [python]
  